name: face_detection_practice
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  camera: ^0.10.5+2
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.7.0
  image: ^4.0.17
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
